name: python2
channels:
- bioconda
- conda-forge
- ome
dependencies:
# bioconda
- zeroc-ice36-python
# conda-forge
- ipywidgets=7.4.*
- matplotlib=3.1.*
- pandas=0.25.*
- pillow=6.*
- pytables=3.4.*
- pytest=5.2.*
- python=3.6.*
- scikit-image=0.16.*
- scipy=1.3.*
- pip:
  - omero-py==5.6.dev3